# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Quran.sh
tagline: "Truth, History, and Interpretation"
description: "Quran.sh is a website dedicated to exploring the truth of the Quran through in-depth analysis, discussion, and examination of its claims and teachings."
url: "https://quran.sh"
baseurl: ""
default_links: |
  - [Orthodox Shahada](https://www.youtube.com/@OrthodoxShahada)
  - [Apostate Prophet](https://www.youtube.com/@ApostateProphet)

author:
  name: "Mark Otto"
  url: https://twitter.com/mdo

# Custom vars
version: 0.1

github:
  repo: https://github.com/likeich/quran.sh

collections:
  issues:
    output: true
  miracles:
    output: true
  errors:
    output: true
  quran:
    output: true
