# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Quran.sh
tagline: "A Jekyll theme"
description: "Silencing the Quran"
url: "https://likeich.github.io"
baseurl: "/quran.sh/"

author:
  name: "Mark Otto"
  url: https://twitter.com/mdo

paginate: 5
paginate_path: "/page:num/" # Pagination URLs

# Plugins (include pagination)
plugins:
  - jekyll-paginate

# Custom vars
version: 0.1

github:
  repo: https://github.com/likeich/quran.sh
